server:
  port: 887
security:
  oauth2:
    client:
      id: server
      client-id: SampleClientId
      client-secret: 123456
      grant-type: authorization_code
      scope: read
      access-token-uri: http://localhost:888/oauth/token
      user-authorization-uri: http://localhost:888/oauth/authorize
      check-token-uri: http://localhost:888/oauth/check_token
      pre-established-redirect-uri: /login
    resource:
      user-info-uri: http://localhost:888/user/me

spring:
  thymeleaf:
    cache: false
logging:
  level:
    root: info
    org.springframework.security: debug
  path: /data/logs/oauth2/client
  file.max-history: 150

host:
  api: http://api.sso.com