server:
  port: 886

spring:
  thymeleaf:
    cache: false

logging:
  level:
    root: info
  org:
    springframework:
      security: debug
  path: /data/logs/oauth2/resource
  file:
    max-history: 150

tokenKeyUri: http://localhost:888/oauth/token_key